const StudentActionTypes = {
    FETCH_ALL_STUDENTS : "FETCH_ALL_STUDENTS",
    CREATE_NEW_STUDENT : "CREATE_NEW_STUDENT",
    DELETE_STUDENT: "DELETE_STUDENT",
    FETCH_SINGLE_STUDENT: "FETCH_SINGLE_STUDENT",

}

export default StudentActionTypes;