const CampusActionType = {
  FETCH_ALL_CAMPUSES: "FETCH_ALL_CAMPUSES",
  CREATE_NEW_CAMPUS: "CREATE_NEW_CAMPUS",
  DELETE_CAMPUS: "DELETE_CAMPUS",
  FETCH_SINGLE_CAMPUS: "FETCH_SINGLE_CAMPUS",
  UPDATE_CAMPUS: "UPDATE_CAMPUS",
};

export default CampusActionType;
